site_name: DIH2 STAR
site_url: https://github.com/STAR
repo_url: https://github.com/STAR
site_description: RAMP Documentation
docs_dir: docs
site_dir: html
edit_uri: edit/master/doc/
markdown_extensions: [toc,fenced_code]
use_directory_urls: true
theme: readthedocs
pages:
  - Home: 'README.md'
  - 'Getting Started' : 'getting-started.md'
  - 'User & Programmers Manual':
    - 'Architecture' : 'architecture.md'
    - 'API' : 'api.md'
    - 'User Guide': 'usermanual.md'
    - 'ROSE AP Guide': 'roseapmanual.md'
  - 'Installation & Administration Manual': 
    - 'Installation Guide': 'installationguide.md'
    